//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerFA.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PerFAEntities1 : DbContext
    {
        public PerFAEntities1()
            : base("name=PerFAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Credit> Credits { get; set; }
        public virtual DbSet<Deposit> Deposits { get; set; }
        public virtual DbSet<Grant> Grants { get; set; }
        public virtual DbSet<HouseholdExpence> HouseholdExpences { get; set; }
        public virtual DbSet<LongTermExpence> LongTermExpences { get; set; }
        public virtual DbSet<OtherExpence> OtherExpences { get; set; }
        public virtual DbSet<OtherIncome> OtherIncomes { get; set; }
        public virtual DbSet<Rent> Rents { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<TransactionUser> TransactionUsers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Wage> Wages { get; set; }
    }
}
