//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerFA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public int ID { get; set; }
        public Nullable<decimal> Deposit_rate___ { get; set; }
        public Nullable<decimal> Money_on_deposit { get; set; }
        public Nullable<decimal> Expected_income { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
