//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerFA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int ID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Meters { get; set; }
        public Nullable<decimal> Public_utilities { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
